# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap

# Site settings
title: Christian Balcom's projects.
email: robot.inventor@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://computer-whisperer.github.io" # the base hostname & protocol for your site
paginate: 5
twitter_username: christianbalcom
github_username:  computer-whisperer
#excerpt_separator: <!--more-->

# Build settings
markdown: kramdown


# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/computer-whisperer/compuiter-whisperer.github.io